-- MySQL Script generated by MySQL Workbench
-- Fri Oct 22 14:47:16 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema food-at-my-hood
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema food-at-my-hood
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `food-at-my-hood` DEFAULT CHARACTER SET utf8 ;
USE `food-at-my-hood` ;

-- -----------------------------------------------------
-- Table `food-at-my-hood`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food-at-my-hood`.`customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NULL,
  `mobile_number` INT NULL,
  `email` VARCHAR(20) NULL,
  `password` VARCHAR(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `food-at-my-hood`.`menu_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food-at-my-hood`.`menu_item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NULL,
  `price` INT NULL,
  `url` VARCHAR(2000) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `food-at-my-hood`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food-at-my-hood`.`cart` (
  `id` INT NOT NULL,
  `customer_id` INT NULL,
  `food_id` INT NULL,
  `quantity` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_customer_idx` (`customer_id` ASC) VISIBLE,
  INDEX `fk_food_idx` (`food_id` ASC) VISIBLE,
  CONSTRAINT `fk_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `food-at-my-hood`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_food`
    FOREIGN KEY (`food_id`)
    REFERENCES `food-at-my-hood`.`menu_item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
